export const CHAIN_LOCAL_WALLET = 'CHAIN_LOCAL_WALLET';
export const CHAIN_LOCAL_CONNECTION = 'CHAIN_LOCAL_CONNECTION';
export const CHAIN_LOCAL_CLIENT = 'CHAIN_LOCAL_CLIENT';
export const CHAIN_GAME = 'CHAIN_GAME';
export const CHAIN_PLAYER = 'CHAIN_PLAYER';
export const CHAIN_NEXT_TURN = 'CHAIN_NEXT_TURN';
export const CHAIN_PROGRAM = 'CHAIN_PROGRAM';
